"""empty message

Revision ID: 2946fde12826
Revises: None
Create Date: 2016-02-03 11:42:38.957566

"""

# revision identifiers, used by Alembic.
revision = '2946fde12826'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('dateAdded', sa.Date(), nullable=True),
    sa.Column('datePlanned', sa.Date(), nullable=True),
    sa.Column('dateCompleted', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    ### end Alembic commands ###
